language: ruby
sudo: false
addons:
  apt_packages:
    - pandoc
    # - pandoc-citeproc # no available, yet
    - wkhtmltopdf
    - libimage-exiftool-perl
branches:
  only:
    - trunk
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - apt-get download pandoc-citeproc || wget http://us.archive.ubuntu.com/ubuntu/pool/universe/h/haskell-pandoc-citeproc/pandoc-citeproc_0.4.0.1-1build1_amd64.deb
  - apt-get download libghc-pandoc-citeproc-data || wget http://us.archive.ubuntu.com/ubuntu/pool/universe/h/haskell-pandoc-citeproc/libghc-pandoc-citeproc-prof_0.4.0.1-1build1_amd64.deb
  - dpkg --unpack --root=$HOME libghc*.deb
  - dpkg --unpack --root=$HOME pandoc-citeproc*.deb
  - bundle install
  - export PATH=$PATH:$HOME/bin:$HOME/usr/bin
script:
  - rake
after_success:
  - mv static ../
  - git branch -D master || 0
  - git checkout --orphan master
  - rm -rf *
  - mv ../static/* .
  - git config --global user.email "travis-ci@travis.org"
  - git config --global user.name "Travis CI"
  - git add --all .
  - git commit -am "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - git push -fq origin master:master
