language: ruby
sudo: false
addons:
  apt_packages:
    - pandoc
    - pandoc-citeproc
    - wkhtmltopdf
    - libimage-exiftool-perl
branches:
  only:
    - trunk
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - export PATH=$PATH:~/.cabal/bin/
  - bundle install
script:
  - rake
after_success:
  - mv static ../
  - git branch -D master || 0
  - git checkout --orphan master
  - rm -rf *
  - mv ../static/* .
  - git config --global user.email "travis-ci@travis.org"
  - git config --global user.name "Travis CI"
  - git add --all .
  - git commit -am "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - git push -fq origin master:master
