language: ruby
sudo: false
addons:
  apt_packages:
    - pandoc
    - wkhtmltopdf
branches:
  only:
    - trunk
install:
  - bundle install
  - curl http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.00.tar.gz | tar -xzf -
  - export PATH=$PATH:$(pwd)/Image-ExifTool-*/
script:
  - rake
after_success:
  - mv static ../
  - git branch -D master || 0
  - git checkout --orphan master
  - rm -rf *
  - mv ../static/* .
  - git config --global user.email "travis-ci@travis.org"
  - git config --global user.name "Travis CI"
  - git add --all .
  - git commit -am "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - git push -fq origin master:master
